services:
  nginx:
    image: nginx:latest
    container_name: classroom-nginx
    ports:
      - "80:80"
      - "443:443" # Expose port 443 for HTTPS
    volumes:
      - ../Frontend/dist:/usr/share/nginx/html
      - ./nginx-simple/nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot_certs:/etc/letsencrypt # Volume for Let's Encrypt certificates
      - acme_challenge:/var/www/certbot # Volume for Certbot ACME challenge
    depends_on:
      - api
      - minio
    restart: unless-stopped

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: classroom-api
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DOMAIN_NAME=your_actual_domain.com # Add your domain name here
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=myclassroomdb
      - DB_USER=avnadmin
      - DB_PASSWORD=yourpassword
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_EXTERNAL_ENDPOINT=/minio
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadminpassword
      - JWT_SECRET=your-production-jwt-secret-change-this
      - JWT_EXPIRATION=1h
      - DOMAIN_NAME=classroom.set4.me # Ensure your domain is set
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: classroom-db
    environment:
      POSTGRES_USER: avnadmin
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: myclassroomdb
      TZ: 'GMT+5:30'
      PGTZ: 'GMT+5:30'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U avnadmin -d myclassroomdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  minio:
    image: quay.io/minio/minio
    container_name: classroom-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    command: server /data --console-address ":9090"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  certbot: # New Certbot service
    image: certbot/certbot
    container_name: classroom-certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
      - acme_challenge:/var/www/certbot
    # Command to renew certificates automatically
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet && sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx

  minio-init:
    image: quay.io/minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadminpassword;
      /usr/bin/mc mb myminio/classroom-uploads --ignore-existing;
      /usr/bin/mc policy set private myminio/classroom-uploads;
      echo 'MinIO bucket setup completed';
      exit 0;
      "

volumes:
  postgres_data:
  minio_data:
  certbot_certs: {} # Define certbot_certs volume
  acme_challenge: {} # Define acme_challenge volume
