version: '3.8' # Or your main compose file's version
services:
  nginx:
    volumes:
      # This volume overrides the main nginx config to use the http-only version
      - ./nginx-simple/nginx-http-only.conf:/etc/nginx/conf.d/default.conf:ro
      # These volumes are still needed for Certbot to function
      - certbot_certs:/etc/letsencrypt
      - acme_challenge:/var/www/certbot
    ports:
      - "80:80" # Only port 80 is exposed for the ACME challenge
